version: '3'

services:

  db: 
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/lib/mysql
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network
     
  app:
    build:
      context: ./node
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    container_name: app
    tty: true
    volumes:
      - ./:/usr/src/app
    networks:
      - node-network
    depends_on:
      - db

  node:
    build: 
      context: ./node
      dockerfile: Dockerfile
    image: 270992/node
    container_name: node-server
    networks: 
      - node-network
    ports:
      - "8080:8080"
      
  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    image: 270992/nginx
    container_name: nginx
    networks: 
      - node-network
    depends_on:
      - node

networks:
  node-network:
    driver: bridge
